apiVersion: v1
kind: Secret
metadata:
  name: hospital-secret
type: Opaque
stringData:
  ADMIN_PASSWORD: {{ .Values.secret.ADMIN_PASSWORD }}
  SESSION_SECRET: {{ .Values.secret.SESSION_SECRET }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET }}