apiVersion: v1
kind: Service
metadata:
  name: hospital-service
spec:
  type: LoadBalancer
  selector:
    app: hospital
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}